"""Deterministic JSON schema export for public eSlams contracts."""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any

from eslams.contracts.integrity import ATTEMPT_KINDS, FAILURE_CLASSES
from eslams.contracts.pricing import no_secret_example as price_card_no_secret_example
from eslams.contracts.provider import GATEWAY_MODES, PROVIDER_OUTCOMES
from eslams.contracts.versions import (
    ACTION_PROVENANCE_SCHEMA_VERSION,
    ARENA_ACTION_DESCRIPTOR_SCHEMA_VERSION,
    ARENA_EVENT_SCHEMA_VERSION,
    ARENA_LEGAL_ACTIONS_PAGE_SCHEMA_VERSION,
    ARENA_START_RESULT_SCHEMA_VERSION,
    ARENA_STEP_RESULT_SCHEMA_VERSION,
    ARTIFACT_MANIFEST_SCHEMA_VERSION,
    ARTIFACT_VALIDATION_SCHEMA_VERSION,
    CATALOGUE_AVAILABILITY_SCHEMA_VERSION,
    CATALOGUE_GAME_SCHEMA_VERSION,
    CATALOGUE_MODEL_SCHEMA_VERSION,
    CATALOGUE_RENDERER_SCHEMA_VERSION,
    CORE_OBSERVABILITY_SCHEMA_VERSION,
    CORE_PACKAGE_VERSION,
    CORE_PROMPT_PACKAGE_SCHEMA_VERSION,
    CORE_REPLAY_EVENT_SCHEMA_VERSION,
    CORE_RUNNER_SESSION_SCHEMA_VERSION,
    CORE_STEP_REQUEST_SCHEMA_VERSION,
    CORE_STEP_RESPONSE_SCHEMA_VERSION,
    EVAL_PLAN_SCHEMA_VERSION,
    EVAL_PROGRESS_SCHEMA_VERSION,
    EVAL_RESUME_CHECKPOINT_SCHEMA_VERSION,
    GAME_ANIMATION_SCHEMA_VERSION,
    GAME_HELP_SCHEMA_VERSION,
    GAME_RENDER_SCHEMA_VERSION,
    GAME_RESULT_SCHEMA_VERSION,
    GAME_SURFACE_SCHEMA_VERSION,
    GAME_TOPOLOGY_SCHEMA_VERSION,
    OFFICIAL_RESULT_SCHEMA_VERSION,
    PRICE_CARD_REFERENCE_SCHEMA_VERSION,
    PROVIDER_ATTEMPT_SCHEMA_VERSION,
    PROVIDER_RECEIPT_SCHEMA_VERSION,
    PUBLICATION_BUNDLE_SCHEMA_VERSION,
    PUBLICATION_VALIDATION_SCHEMA_VERSION,
    REPLAY_DISPLAY_FRAME_SCHEMA_VERSION,
    REPLAY_MANIFEST_SCHEMA_VERSION,
    REPLAY_PUBLIC_SCHEMA_VERSION,
    RUN_INTEGRITY_SCHEMA_VERSION,
    RUNNER_JOB_SCHEMA_VERSION,
    SCHEMA_BUNDLE_MANIFEST_SCHEMA_VERSION,
    SCHEMA_BUNDLE_VERSION,
    USAGE_SCHEMA_VERSION,
    USAGE_SUMMARY_SCHEMA_VERSION,
    schema_versions,
)
from eslams.hashing import canonical_json, sha256_file, sha256_json

SCHEMA_BUNDLE_MANIFEST_FILENAME = "schema_bundle_manifest.json"
SCHEMA_BUNDLE_BUILD_ID = "1970-01-01T00:00:00Z"


def export_schemas(output_dir: Path) -> list[Path]:
    """Write every known contract schema with deterministic bytes."""

    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for version in schema_versions():
        path = output_dir / schema_filename(version)
        path.write_text(canonical_json(schema_for_version(version)) + "\n", encoding="utf-8")
        written.append(path)
    manifest_path = output_dir / SCHEMA_BUNDLE_MANIFEST_FILENAME
    manifest_path.write_text(
        canonical_json(schema_bundle_manifest(written)) + "\n",
        encoding="utf-8",
    )
    written.append(manifest_path)
    return written


def schema_filename(version: str) -> str:
    return f"{version}.schema.json"


def schema_for_version(version: str) -> dict[str, Any]:
    schemas = _schemas()
    if version not in schemas:
        raise KeyError(f"unknown schema version {version!r}")
    return schemas[version]


def schema_bundle_manifest(schema_paths: list[Path]) -> dict[str, Any]:
    schema_rows = []
    for path in sorted(schema_paths, key=lambda item: item.name):
        if path.name == SCHEMA_BUNDLE_MANIFEST_FILENAME:
            continue
        version = path.name.removesuffix(".schema.json")
        schema_rows.append(
            {
                "name": path.name,
                "schema_version": version,
                "sha256": sha256_file(path),
                "bytes": path.stat().st_size,
            }
        )
    return {
        "schema_version": SCHEMA_BUNDLE_MANIFEST_SCHEMA_VERSION,
        "core_package_version": CORE_PACKAGE_VERSION,
        "core_commit": _git_commit(),
        "schema_bundle_version": SCHEMA_BUNDLE_VERSION,
        "deterministic_build_id": sha256_json(
            {
                "core_package_version": CORE_PACKAGE_VERSION,
                "schema_bundle_version": SCHEMA_BUNDLE_VERSION,
                "schemas": schema_rows,
            }
        ),
        "generated_at": SCHEMA_BUNDLE_BUILD_ID,
        "schemas": schema_rows,
    }


def no_secret_examples() -> dict[str, dict[str, Any]]:
    return {
        PRICE_CARD_REFERENCE_SCHEMA_VERSION: price_card_no_secret_example(),
        RUN_INTEGRITY_SCHEMA_VERSION: {
            "schemaVersion": RUN_INTEGRITY_SCHEMA_VERSION,
            "integrityStatus": "valid",
            "validForScoring": True,
            "invalidReasonCodes": [],
            "agentErrorCountByPlayer": {"player_1": 0},
            "fallbackActionCountByPlayer": {"player_1": 0},
            "illegalActionCountByPlayer": {"player_1": 0},
            "providerStatusByPlayer": {"player_1": "provider_ok"},
            "providerActionCountByPlayer": {"player_1": 1},
            "logicalActionCountByPlayer": {"player_1": 1},
            "usageComplete": True,
            "costComplete": True,
            "modelIdentityVerified": True,
            "attemptLedgerComplete": True,
        },
        ACTION_PROVENANCE_SCHEMA_VERSION: {
            "schemaVersion": ACTION_PROVENANCE_SCHEMA_VERSION,
            "eventId": "event_example",
            "runId": "run_example",
            "episodeId": "episode_001",
            "turnId": 0,
            "seatId": "player_1",
            "provenance": "provider_action",
            "logicalActionId": "logical_example",
            "successfulAttemptEventId": "sha256:example",
            "metadata": {},
        },
        USAGE_SUMMARY_SCHEMA_VERSION: {
            "schemaVersion": USAGE_SUMMARY_SCHEMA_VERSION,
            "totalInputTokens": 10,
            "totalOutputTokens": 2,
            "totalCachedInputTokens": 0,
            "totalReasoningTokens": 0,
            "totalTokens": 12,
            "totalCostUsd": None,
            "usageComplete": True,
            "costComplete": False,
            "receiptCount": 1,
            "attemptCount": 1,
            "logicalActionCount": 1,
            "attemptLedgerComplete": True,
            "unavailableReasonCodes": ["pricing_not_configured"],
            "rateCardReferences": [],
        },
        ARENA_ACTION_DESCRIPTOR_SCHEMA_VERSION: {
            "token": "play:AS",
            "label": "Play A\u2660",
            "short_label": "A\u2660",
            "verb": "play",
            "object": "A\u2660",
            "category": "play_card",
            "group": "Play a card",
            "sort_key": "play_card:play_AS",
            "prompt_label": "play A\u2660",
            "confirm": False,
            "disabled_reason": None,
        },
        ARENA_EVENT_SCHEMA_VERSION: {
            "schema_version": ARENA_EVENT_SCHEMA_VERSION,
            "event_id": "arena:example:turn:000001:000:human_action_accepted",
            "type": "human.action.accepted",
            "turn_id": 1,
            "actor": "player_1",
            "action": "e2e4",
            "action_label": "Move e2 to e4",
            "display_frame": {},
            "state_hash": "sha256:example",
            "created_at": "2026-06-09T00:00:00Z",
        },
        ARENA_LEGAL_ACTIONS_PAGE_SCHEMA_VERSION: {
            "schema_version": ARENA_LEGAL_ACTIONS_PAGE_SCHEMA_VERSION,
            "player_id": "player_1",
            "query": None,
            "limit": 50,
            "cursor": None,
            "next_cursor": None,
            "total_legal_actions": 1,
            "total_matching_actions": 1,
            "has_more": False,
            "rows": [
                {
                    "token": "e2e4",
                    "label": "Move e2 to e4",
                    "short_label": "e2-e4",
                    "verb": "move",
                    "object": "e4",
                    "category": "move_piece",
                    "group": "Move a piece",
                    "sort_key": "move_piece:e2e4",
                    "prompt_label": "move e2 to e4",
                    "confirm": False,
                    "disabled_reason": None,
                }
            ],
        },
        ARENA_START_RESULT_SCHEMA_VERSION: {
            "schema_version": ARENA_START_RESULT_SCHEMA_VERSION,
            "session_state": {},
            "state_hash": "sha256:example",
            "state_hash_status": "verified",
            "public_state": {},
            "display_frame": {},
            "active_player": "player_1",
            "next_actor_kind": "human",
            "terminal": False,
            "outcome": None,
            "scores": None,
            "legal_actions": ["e2e4"],
            "legal_action_descriptors": [],
            "total_legal_actions": 1,
            "total_matching_legal_actions": 1,
            "has_more_legal_actions": False,
            "legal_actions_cursor": None,
            "events": [],
            "timing": {"total_core_ms": 1},
        },
        ARENA_STEP_RESULT_SCHEMA_VERSION: {
            "schema_version": ARENA_STEP_RESULT_SCHEMA_VERSION,
            "accepted": True,
            "turn_id": 1,
            "session_state": {},
            "state_hash": "sha256:example",
            "state_hash_status": "verified",
            "public_state": {},
            "display_frame": {},
            "active_player": "player_2",
            "next_actor_kind": "model",
            "terminal": False,
            "outcome": None,
            "scores": None,
            "legal_actions": [],
            "legal_action_descriptors": [],
            "total_legal_actions": 0,
            "total_matching_legal_actions": 0,
            "has_more_legal_actions": False,
            "legal_actions_cursor": None,
            "events": [],
            "timing": {"total_core_ms": 1},
            "error": None,
        },
        CORE_STEP_REQUEST_SCHEMA_VERSION: {
            "coreContractVersion": "2.0",
            "gameId": "tic-tac-toe",
            "rulesetVersion": "standard",
            "state": {},
            "action": {"actionId": "4"},
            "actorId": "player_1",
            "requestId": "req_example",
            "deadlineMs": 2000,
            "includeObservation": True,
            "includeLegalActions": "compact",
            "includeReplayEvent": True,
        },
        CORE_STEP_RESPONSE_SCHEMA_VERSION: {
            "coreVersion": CORE_PACKAGE_VERSION,
            "coreContractVersion": "2.0",
            "ok": True,
            "gameId": "tic-tac-toe",
            "rulesetVersion": "standard",
            "previousStateHash": "sha256:before",
            "actionHash": "sha256:action",
            "nextStateHash": "sha256:after",
            "legalActionHashBefore": "sha256:legal-before",
            "legalActionHashAfter": "sha256:legal-after",
            "state": {},
            "observation": {},
            "legalActions": {"include": "compact", "count": 0, "hash": "sha256:legal"},
            "replayEvent": {},
            "terminal": {"terminal": False, "outcome": None, "scores": {}},
            "error": None,
            "timingsMs": {"receivedAt": "2026-06-11T00:00:00Z", "totalMs": 1},
        },
        CORE_PROMPT_PACKAGE_SCHEMA_VERSION: {
            "gameId": "tic-tac-toe",
            "rulesetVersion": "standard",
            "promptVersion": "eslams.core.prompt.v2",
            "stablePrefix": [],
            "dynamicTurn": {
                "moveHistory": "[]",
                "currentObservation": "{}",
                "legalActions": "{}",
            },
            "outputSchema": {},
            "parserVersion": "eslams.model_actions.v1",
            "promptHash": "sha256:prompt",
            "tokenEstimate": 128,
        },
        CORE_REPLAY_EVENT_SCHEMA_VERSION: {
            "schemaVersion": CORE_REPLAY_EVENT_SCHEMA_VERSION,
            "seq": 1,
            "turn": 1,
            "type": "action_applied",
            "gameId": "tic-tac-toe",
            "actorId": "player_1",
            "actionHash": "sha256:action",
            "previousStateHash": "sha256:before",
            "nextStateHash": "sha256:after",
            "timestamp": "2026-06-11T00:00:00Z",
            "timingsMs": {},
            "payload": {},
        },
        CORE_RUNNER_SESSION_SCHEMA_VERSION: {
            "schemaVersion": CORE_RUNNER_SESSION_SCHEMA_VERSION,
            "sessionId": "arena_example",
            "gameId": "tic-tac-toe",
            "stateHash": "sha256:state",
            "turn": 0,
            "ok": True,
        },
        CORE_OBSERVABILITY_SCHEMA_VERSION: {
            "event": "core.step.completed",
            "requestId": "req_example",
            "gameId": "tic-tac-toe",
            "coreVersion": CORE_PACKAGE_VERSION,
            "engineImpl": "python_core",
            "stateBytes": 100,
            "observationBytes": 120,
            "legalActionCount": 9,
            "timingsMs": {},
        },
        SCHEMA_BUNDLE_MANIFEST_SCHEMA_VERSION: {
            "schema_version": SCHEMA_BUNDLE_MANIFEST_SCHEMA_VERSION,
            "core_package_version": CORE_PACKAGE_VERSION,
            "core_commit": "abcdef1234567890",
            "schema_bundle_version": SCHEMA_BUNDLE_VERSION,
            "deterministic_build_id": "sha256:example",
            "generated_at": SCHEMA_BUNDLE_BUILD_ID,
            "schemas": [
                {
                    "name": "eslams.artifact.validation.v1.schema.json",
                    "schema_version": ARTIFACT_VALIDATION_SCHEMA_VERSION,
                    "sha256": "sha256:example",
                    "bytes": 123,
                }
            ],
        },
    }


def _schemas() -> dict[str, dict[str, Any]]:
    return {
        ARTIFACT_MANIFEST_SCHEMA_VERSION: _object_schema(
            ARTIFACT_MANIFEST_SCHEMA_VERSION,
            required=["manifest_schema_version", "artifact_profile", "artifact_kind", "run_id"],
            properties={
                "manifest_schema_version": {"const": ARTIFACT_MANIFEST_SCHEMA_VERSION},
                "artifact_profile": {"type": "string"},
                "artifact_kind": {"type": "string"},
                "run_id": {"type": "string"},
                "artifact_id": {"type": "string"},
                "verification_level_key": {"type": "string"},
                "verification_level_label": {"type": "string"},
                "artifact_profile_key": {"type": "string"},
                "artifact_profile_label": {"type": "string"},
                "scoring_policy_key": {"type": "string"},
                "scoring_policy_label": {"type": "string"},
                "per_case_run_valid": {"type": "boolean"},
                "per_case_scoring_eligible": {"type": "boolean"},
                "proof_row_publication_eligible": {"type": "boolean"},
                "aggregate_leaderboard_eligible": {"type": "boolean"},
                "aggregate_ineligibility_reason": {"type": ["string", "null"]},
                "files": {"type": "array"},
            },
        ),
        ARTIFACT_VALIDATION_SCHEMA_VERSION: _object_schema(
            ARTIFACT_VALIDATION_SCHEMA_VERSION,
            required=["schema_version", "artifact", "profile", "valid", "validation_status"],
            properties={
                "schema_version": {"const": ARTIFACT_VALIDATION_SCHEMA_VERSION},
                "artifact": {"type": "string"},
                "profile": {"type": "string"},
                "valid": {"type": "boolean"},
                "validation_status": {"type": "string"},
                "errors": {"type": "array", "items": {"type": "string"}},
                "signature": {"type": "object"},
                "deterministic_replay": {"type": "object"},
                "per_case_run_valid": {"type": ["boolean", "null"]},
                "per_case_scoring_eligible": {"type": ["boolean", "null"]},
                "proof_row_publication_eligible": {"type": ["boolean", "null"]},
                "aggregate_leaderboard_eligible": {"type": ["boolean", "null"]},
                "aggregate_ineligibility_reason": {"type": ["string", "null"]},
            },
        ),
        REPLAY_PUBLIC_SCHEMA_VERSION: _object_schema(
            REPLAY_PUBLIC_SCHEMA_VERSION,
            required=["schema_version", "event_id", "run_id", "turn_id", "public_safe"],
            properties={
                "schema_version": {"const": REPLAY_PUBLIC_SCHEMA_VERSION},
                "event_id": {"type": "string"},
                "run_id": {"type": "string"},
                "turn_id": {"type": "integer"},
                "actor_player": {"type": ["string", "null"]},
                "seat": {"type": ["string", "null"]},
                "public_safe": {"type": "boolean"},
            },
        ),
        REPLAY_MANIFEST_SCHEMA_VERSION: _object_schema(
            REPLAY_MANIFEST_SCHEMA_VERSION,
            required=["schema_version", "replay_id", "run_id", "event_count"],
            properties={
                "schema_version": {"const": REPLAY_MANIFEST_SCHEMA_VERSION},
                "replay_id": {"type": "string"},
                "run_id": {"type": "string"},
                "arena_id": {"type": "string"},
                "event_count": {"type": "integer"},
                "timeline_completeness": {"type": "string"},
                "participants": {"type": "array"},
            },
        ),
        REPLAY_DISPLAY_FRAME_SCHEMA_VERSION: _object_schema(
            REPLAY_DISPLAY_FRAME_SCHEMA_VERSION,
            required=[
                "schema_version",
                "frame_id",
                "renderer_family",
                "visibility",
                "source_replay_event_id",
            ],
            properties={
                "schema_version": {"const": REPLAY_DISPLAY_FRAME_SCHEMA_VERSION},
                "frame_id": {"type": "string"},
                "renderer_family": {"type": "string"},
                "visibility": {"type": "string"},
                "actor_player": {"type": ["string", "null"]},
                "action_label": {"type": ["string", "null"]},
                "display_cells": {"type": "array"},
                "summary": {"type": "object"},
                "source_replay_event_id": {"type": "string"},
            },
        ),
        RUN_INTEGRITY_SCHEMA_VERSION: _object_schema(
            RUN_INTEGRITY_SCHEMA_VERSION,
            required=[
                "schemaVersion",
                "integrityStatus",
                "validForScoring",
                "invalidReasonCodes",
                "usageComplete",
                "costComplete",
                "modelIdentityVerified",
                "attemptLedgerComplete",
            ],
            properties={
                "schemaVersion": {"const": RUN_INTEGRITY_SCHEMA_VERSION},
                "integrityStatus": {"enum": ["valid", "invalid", "incomplete"]},
                "validForScoring": {"type": "boolean"},
                "invalidReasonCodes": {"type": "array", "items": {"type": "string"}},
                "agentErrorCountByPlayer": {"type": "object"},
                "fallbackActionCountByPlayer": {"type": "object"},
                "illegalActionCountByPlayer": {"type": "object"},
                "providerStatusByPlayer": {"type": "object"},
                "providerActionCountByPlayer": {"type": "object"},
                "logicalActionCountByPlayer": {"type": "object"},
                "usageComplete": {"type": "boolean"},
                "costComplete": {"type": "boolean"},
                "modelIdentityVerified": {"type": "boolean"},
                "attemptLedgerComplete": {"type": "boolean"},
            },
        ),
        ACTION_PROVENANCE_SCHEMA_VERSION: _object_schema(
            ACTION_PROVENANCE_SCHEMA_VERSION,
            required=[
                "schemaVersion",
                "eventId",
                "runId",
                "episodeId",
                "turnId",
                "seatId",
                "provenance",
                "logicalActionId",
            ],
            properties={
                "schemaVersion": {"const": ACTION_PROVENANCE_SCHEMA_VERSION},
                "eventId": {"type": "string"},
                "runId": {"type": "string"},
                "episodeId": {"type": "string"},
                "turnId": {"type": "integer"},
                "seatId": {"type": "string"},
                "provenance": {"enum": ["provider_action", "local_action", "fallback_action"]},
                "logicalActionId": {"type": "string"},
                "successfulAttemptEventId": {"type": ["string", "null"]},
                "metadata": {"type": "object"},
            },
        ),
        PROVIDER_ATTEMPT_SCHEMA_VERSION: _provider_attempt_schema(),
        PROVIDER_RECEIPT_SCHEMA_VERSION: _object_schema(
            PROVIDER_RECEIPT_SCHEMA_VERSION,
            required=[
                "schema_version",
                "provider",
                "model",
                "outcome",
                "environment",
                "physical_run_id",
                "run_id",
                "official_run_id",
                "model_lane_id",
                "run_job_id",
                "agent_id",
                "turn_id",
                "case_id",
                "case_attempt_index",
                "shard_index",
                "attempt",
                "attempt_index",
                "event_id",
                "logical_action_id",
                "attempt_kind",
                "status",
                "usage_complete",
                "cost_complete",
                "wire_parse_status",
                "action_parse_status",
                "action_applied",
                "case_valid_for_scoring",
                "redaction_version",
            ],
            properties={
                "schema_version": {"const": PROVIDER_RECEIPT_SCHEMA_VERSION},
                "provider": {"type": "string"},
                "model": {"type": "string"},
                "locked_model_id": {"type": ["string", "null"]},
                "model_identity_source": {"type": ["string", "null"]},
                "endpoint_kind": {"type": ["string", "null"]},
                "parser_version": {"type": ["string", "null"]},
                "agent_id": {"type": "string", "minLength": 1},
                "agent_version": {"type": ["string", "null"]},
                "turn_id": {"type": "integer", "minimum": 0},
                "environment": {"type": "string", "minLength": 1},
                "physical_run_id": {"type": "string", "minLength": 1},
                "run_id": {"type": "string", "minLength": 1},
                "official_run_id": {"type": "string", "minLength": 1},
                "model_lane_id": {"type": "string", "minLength": 1},
                "run_job_id": {"type": "string", "minLength": 1},
                "episode_id": {"type": ["string", "null"]},
                "case_id": {"type": ["string", "null"]},
                "case_attempt_index": {"type": "integer", "minimum": 1},
                "shard_index": {"type": ["integer", "null"], "minimum": 0},
                "attempt": {"type": "integer", "minimum": 1},
                "attempt_index": {"type": "integer", "minimum": 1},
                "event_id": {"type": "string", "minLength": 1},
                "logical_action_id": {"type": "string", "minLength": 1},
                "active_player": {"type": ["string", "null"]},
                "seat_id": {"type": ["string", "null"]},
                "attempt_kind": {"enum": list(ATTEMPT_KINDS)},
                "parent_attempt_id": {"type": ["string", "null"]},
                "outcome": {"enum": list(PROVIDER_OUTCOMES)},
                "status": {"enum": ["started", "completed", "failed"]},
                "status_code": {
                    "type": ["integer", "null"],
                    "minimum": 100,
                    "maximum": 599,
                },
                "request_id": {"type": ["string", "null"]},
                "gateway_mode": {"enum": list(GATEWAY_MODES)},
                "gateway_request_id": {"type": ["string", "null"]},
                "latency_ms": {"type": ["integer", "null"], "minimum": 0},
                "usage": {"type": "object"},
                "usage_unavailable_reason": {"type": ["string", "null"]},
                "pricing": {"type": "object"},
                "estimated_cost": {"type": "object"},
                "rate_card_reference": {"type": ["object", "null"]},
                "rate_card_id": {"type": ["string", "null"]},
                "reasoning_included_in_output": {"type": ["boolean", "null"]},
                "usage_source": {"type": ["string", "null"]},
                "usage_complete": {"type": "boolean"},
                "cost_source": {"type": ["string", "null"]},
                "cost_complete": {"type": "boolean"},
                "wire_parse_status": {
                    "enum": ["ok", "failed", "not_attempted"]
                },
                "action_parse_status": {
                    "enum": ["ok", "failed", "not_attempted"]
                },
                "action_applied": {"type": "boolean"},
                "case_valid_for_scoring": {"type": "boolean"},
                "model_capability_known": {"type": "boolean"},
                "game_agent_supported": {"type": "boolean"},
                "capability_sources": {"type": "array", "items": {"type": "string"}},
                "provider_response_id": {"type": ["string", "null"]},
                "finish_reason": {"type": ["string", "null"]},
                "finish_status": {"type": ["string", "null"]},
                "retry_after_ms": {"type": ["integer", "null"], "minimum": 0},
                "pricing_provenance": {"type": ["object", "null"]},
                "endpoint_metadata": {"type": "object"},
                "record_hash": {"type": "string"},
                "redaction_version": {"type": "string"},
            },
        ),
        PRICE_CARD_REFERENCE_SCHEMA_VERSION: {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$id": (f"https://schemas.eslams.dev/{PRICE_CARD_REFERENCE_SCHEMA_VERSION}.json"),
            "title": PRICE_CARD_REFERENCE_SCHEMA_VERSION,
            "type": "object",
            "additionalProperties": False,
            "required": [
                "schemaVersion",
                "rateCardId",
                "rateCardHash",
                "provider",
                "model",
                "currency",
                "sourceUri",
                "effectiveAt",
                "retrievedAt",
                "complete",
            ],
            "properties": {
                "schemaVersion": {"const": PRICE_CARD_REFERENCE_SCHEMA_VERSION},
                "rateCardId": {"type": "string", "minLength": 1},
                "rateCardHash": {"type": "string", "pattern": "^sha256:[0-9a-f]{64}$"},
                "provider": {"type": "string", "minLength": 1},
                "model": {"type": "string", "minLength": 1},
                "currency": {"const": "USD"},
                "sourceUri": {"type": "string", "minLength": 1},
                "effectiveAt": {"type": ["string", "null"]},
                "retrievedAt": {"type": ["string", "null"]},
                "complete": {"const": True},
            },
        },
        EVAL_PLAN_SCHEMA_VERSION: _object_schema(
            EVAL_PLAN_SCHEMA_VERSION,
            required=["schema_version", "kind", "plan_hash", "case_count_expected", "shards"],
            properties={
                "schema_version": {"const": EVAL_PLAN_SCHEMA_VERSION},
                "kind": {"type": "string"},
                "plan_hash": {"type": "string"},
                "case_count_expected": {"type": "integer"},
                "shards": {"type": "array"},
            },
        ),
        EVAL_PROGRESS_SCHEMA_VERSION: _object_schema(
            EVAL_PROGRESS_SCHEMA_VERSION,
            required=[
                "schema_version",
                "plan_hash",
                "total_cases",
                "completed_cases",
                "failed_cases",
                "skipped_cases",
            ],
            properties={
                "schema_version": {"const": EVAL_PROGRESS_SCHEMA_VERSION},
                "plan_hash": {"type": ["string", "null"]},
                "current_case": {"type": ["string", "null"]},
                "total_cases": {"type": "integer"},
                "completed_cases": {"type": "integer"},
                "failed_cases": {"type": "integer"},
                "skipped_cases": {"type": "integer"},
                "case_rate": {"type": ["number", "null"]},
                "provider_latency_rolling_stats": {"type": "object"},
                "estimated_remaining_time_seconds": {"type": ["number", "null"]},
            },
        ),
        EVAL_RESUME_CHECKPOINT_SCHEMA_VERSION: _object_schema(
            EVAL_RESUME_CHECKPOINT_SCHEMA_VERSION,
            required=["schema_version", "records"],
            properties={
                "schema_version": {"const": EVAL_RESUME_CHECKPOINT_SCHEMA_VERSION},
                "records": {"type": "array"},
            },
        ),
        OFFICIAL_RESULT_SCHEMA_VERSION: _object_schema(
            OFFICIAL_RESULT_SCHEMA_VERSION,
            required=["schema_version"],
            properties={
                "schema_version": {"const": OFFICIAL_RESULT_SCHEMA_VERSION},
                "run_id": {"type": "string"},
                "arena_id": {"type": "string"},
                "winner": {"type": ["string", "null"]},
                "valid_for_scoring": {"type": "boolean"},
                "per_case_run_valid": {"type": "boolean"},
                "per_case_scoring_eligible": {"type": "boolean"},
                "proof_row_publication_eligible": {"type": "boolean"},
                "aggregate_leaderboard_eligible": {"type": "boolean"},
                "aggregate_ineligibility_reason": {"type": ["string", "null"]},
            },
        ),
        PUBLICATION_BUNDLE_SCHEMA_VERSION: _object_schema(
            PUBLICATION_BUNDLE_SCHEMA_VERSION,
            required=[
                "schema_version",
                "kind",
                "object_manifest_hash",
                "completed_object_count",
                "completed_projection_chunk_count",
            ],
            properties={
                "schema_version": {"const": PUBLICATION_BUNDLE_SCHEMA_VERSION},
                "kind": {"type": "string"},
                "publication_kind_key": {"type": "string"},
                "publication_kind_label": {"type": "string"},
                "plan_hash": {"type": ["string", "null"]},
                "suite_fingerprint": {"type": ["string", "null"]},
                "object_manifest_hash": {"type": "string"},
                "statement_projection_hash": {"type": "string"},
                "completed_object_count": {"type": "integer"},
                "completed_projection_chunk_count": {"type": "integer"},
                "artifact_count": {"type": "integer"},
                "aggregate_leaderboard_eligible": {"type": "boolean"},
                "aggregate_ineligibility_reason": {"type": ["string", "null"]},
            },
        ),
        PUBLICATION_VALIDATION_SCHEMA_VERSION: _object_schema(
            PUBLICATION_VALIDATION_SCHEMA_VERSION,
            required=["schema_version", "bundle_dir", "valid", "status", "errors"],
            properties={
                "schema_version": {"const": PUBLICATION_VALIDATION_SCHEMA_VERSION},
                "bundle_dir": {"type": "string"},
                "kind": {"type": ["string", "null"]},
                "valid": {"type": "boolean"},
                "status": {"type": "string"},
                "object_count": {"type": "integer"},
                "projection_chunk_count": {"type": "integer"},
                "errors": {"type": "array", "items": {"type": "string"}},
            },
        ),
        RUNNER_JOB_SCHEMA_VERSION: _object_schema(
            RUNNER_JOB_SCHEMA_VERSION,
            required=["schema_version", "job_id", "arena_id", "artifact_output"],
            properties={
                "schema_version": {"const": RUNNER_JOB_SCHEMA_VERSION},
                "job_id": {"type": "string"},
                "arena_id": {"type": "string"},
                "artifact_output": {"type": "object"},
                "runner_completed": {"type": "boolean"},
                "scoring_eligible": {"type": "boolean"},
                "artifact_uri": {"type": ["string", "null"]},
                "validation_status": {"type": ["string", "null"]},
            },
        ),
        ARENA_ACTION_DESCRIPTOR_SCHEMA_VERSION: _object_schema(
            ARENA_ACTION_DESCRIPTOR_SCHEMA_VERSION,
            required=[
                "token",
                "label",
                "short_label",
                "verb",
                "object",
                "category",
                "group",
                "sort_key",
                "prompt_label",
                "confirm",
                "disabled_reason",
            ],
            properties={
                "token": {"type": "string"},
                "label": {"type": "string"},
                "short_label": {"type": "string"},
                "verb": {"type": "string"},
                "object": {"type": "string"},
                "category": {"type": "string"},
                "group": {"type": "string"},
                "sort_key": {"type": "string"},
                "prompt_label": {"type": "string"},
                "confirm": {"type": "boolean"},
                "disabled_reason": {"type": ["string", "null"]},
            },
        ),
        ARENA_EVENT_SCHEMA_VERSION: _object_schema(
            ARENA_EVENT_SCHEMA_VERSION,
            required=["schema_version", "event_id", "type", "turn_id", "state_hash", "created_at"],
            properties={
                "schema_version": {"const": ARENA_EVENT_SCHEMA_VERSION},
                "event_id": {"type": "string"},
                "type": {"type": "string"},
                "turn_id": {"type": "integer"},
                "actor": {"type": ["string", "null"]},
                "action": {"type": ["string", "null"]},
                "action_label": {"type": ["string", "null"]},
                "display_frame": {"type": "object"},
                "state_hash": {"type": ["string", "null"]},
                "created_at": {"type": "string"},
            },
        ),
        ARENA_LEGAL_ACTIONS_PAGE_SCHEMA_VERSION: _object_schema(
            ARENA_LEGAL_ACTIONS_PAGE_SCHEMA_VERSION,
            required=[
                "schema_version",
                "player_id",
                "total_legal_actions",
                "total_matching_actions",
                "has_more",
                "rows",
            ],
            properties={
                "schema_version": {"const": ARENA_LEGAL_ACTIONS_PAGE_SCHEMA_VERSION},
                "player_id": {"type": "string"},
                "query": {"type": ["string", "null"]},
                "limit": {"type": "integer"},
                "cursor": {"type": ["string", "null"]},
                "next_cursor": {"type": ["string", "null"]},
                "total_legal_actions": {"type": "integer"},
                "total_matching_actions": {"type": "integer"},
                "has_more": {"type": "boolean"},
                "rows": {"type": "array"},
            },
        ),
        ARENA_START_RESULT_SCHEMA_VERSION: _object_schema(
            ARENA_START_RESULT_SCHEMA_VERSION,
            required=[
                "schema_version",
                "session_state",
                "state_hash",
                "public_state",
                "display_frame",
                "active_player",
                "legal_actions",
                "legal_action_descriptors",
                "events",
                "timing",
            ],
            properties={
                "schema_version": {"const": ARENA_START_RESULT_SCHEMA_VERSION},
                "session_state": {"type": "object"},
                "state_hash": {"type": "string"},
                "state_hash_status": {"type": "string"},
                "public_state": {"type": "object"},
                "display_frame": {"type": "object"},
                "active_player": {"type": "string"},
                "next_actor_kind": {"type": ["string", "null"]},
                "terminal": {"type": "boolean"},
                "outcome": {"type": ["object", "null"]},
                "scores": {"type": ["object", "null"]},
                "legal_actions": {"type": "array", "items": {"type": "string"}},
                "legal_action_descriptors": {"type": "array"},
                "total_legal_actions": {"type": "integer"},
                "has_more_legal_actions": {"type": "boolean"},
                "legal_actions_cursor": {"type": ["string", "null"]},
                "events": {"type": "array"},
                "timing": {"type": "object"},
            },
        ),
        ARENA_STEP_RESULT_SCHEMA_VERSION: _object_schema(
            ARENA_STEP_RESULT_SCHEMA_VERSION,
            required=[
                "schema_version",
                "accepted",
                "turn_id",
                "session_state",
                "state_hash_status",
                "public_state",
                "display_frame",
                "events",
                "timing",
            ],
            properties={
                "schema_version": {"const": ARENA_STEP_RESULT_SCHEMA_VERSION},
                "accepted": {"type": "boolean"},
                "turn_id": {"type": "integer"},
                "session_state": {"type": "object"},
                "state_hash": {"type": ["string", "null"]},
                "state_hash_status": {"type": "string"},
                "public_state": {"type": "object"},
                "display_frame": {"type": "object"},
                "active_player": {"type": ["string", "null"]},
                "next_actor_kind": {"type": ["string", "null"]},
                "terminal": {"type": "boolean"},
                "outcome": {"type": ["object", "null"]},
                "scores": {"type": ["object", "null"]},
                "legal_actions": {"type": "array", "items": {"type": "string"}},
                "legal_action_descriptors": {"type": "array"},
                "total_legal_actions": {"type": "integer"},
                "has_more_legal_actions": {"type": "boolean"},
                "legal_actions_cursor": {"type": ["string", "null"]},
                "events": {"type": "array"},
                "timing": {"type": "object"},
                "error": {"type": ["object", "null"]},
            },
        ),
        CORE_STEP_REQUEST_SCHEMA_VERSION: _object_schema(
            CORE_STEP_REQUEST_SCHEMA_VERSION,
            required=[
                "coreContractVersion",
                "gameId",
                "rulesetVersion",
                "state",
                "action",
                "actorId",
                "requestId",
            ],
            properties={
                "coreContractVersion": {"const": "2.0"},
                "gameId": {"type": "string"},
                "rulesetVersion": {"type": "string"},
                "state": {"type": "object"},
                "action": {},
                "actorId": {"type": "string"},
                "requestId": {"type": "string"},
                "turnId": {"type": ["string", "null"]},
                "deadlineMs": {"type": "integer", "minimum": 1},
                "includeObservation": {"type": "boolean"},
                "includeLegalActions": {"enum": ["none", "ids", "compact", "full"]},
                "includeReplayEvent": {"type": "boolean"},
                "observationView": {
                    "enum": ["public_compact", "public_full", "private_actor", "ui_delta", "debug"]
                },
            },
        ),
        CORE_STEP_RESPONSE_SCHEMA_VERSION: _object_schema(
            CORE_STEP_RESPONSE_SCHEMA_VERSION,
            required=[
                "coreVersion",
                "coreContractVersion",
                "ok",
                "gameId",
                "rulesetVersion",
                "previousStateHash",
                "actionHash",
                "timingsMs",
            ],
            properties={
                "coreVersion": {"type": "string"},
                "coreContractVersion": {"const": "2.0"},
                "rulesetVersion": {"type": "string"},
                "promptVersion": {"type": "string"},
                "actionSchemaVersion": {"type": "string"},
                "replaySchemaVersion": {"type": "string"},
                "ok": {"type": "boolean"},
                "gameId": {"type": "string"},
                "requestId": {"type": "string"},
                "previousStateHash": {"type": ["string", "null"]},
                "actionHash": {"type": "string"},
                "nextStateHash": {"type": ["string", "null"]},
                "legalActionHashBefore": {"type": ["string", "null"]},
                "legalActionHashAfter": {"type": ["string", "null"]},
                "state": {"type": ["object", "null"]},
                "observation": {"type": ["object", "null"]},
                "legalActions": {"type": ["object", "null"]},
                "replayEvent": {"type": ["object", "null"]},
                "terminal": {"type": ["object", "null"]},
                "error": {"type": ["object", "null"]},
                "timingsMs": {"type": "object"},
            },
        ),
        CORE_PROMPT_PACKAGE_SCHEMA_VERSION: _object_schema(
            CORE_PROMPT_PACKAGE_SCHEMA_VERSION,
            required=[
                "gameId",
                "rulesetVersion",
                "promptVersion",
                "stablePrefix",
                "dynamicTurn",
                "outputSchema",
                "parserVersion",
                "promptHash",
                "tokenEstimate",
            ],
            properties={
                "gameId": {"type": "string"},
                "rulesetVersion": {"type": "string"},
                "promptVersion": {"type": "string"},
                "stablePrefix": {"type": "array"},
                "dynamicTurn": {"type": "object"},
                "outputSchema": {"type": "object"},
                "parserVersion": {"type": "string"},
                "promptHash": {"type": "string"},
                "tokenEstimate": {"type": "integer"},
            },
        ),
        CORE_REPLAY_EVENT_SCHEMA_VERSION: _object_schema(
            CORE_REPLAY_EVENT_SCHEMA_VERSION,
            required=[
                "schemaVersion",
                "seq",
                "turn",
                "type",
                "actorId",
                "actionHash",
                "previousStateHash",
                "nextStateHash",
                "timingsMs",
                "payload",
            ],
            properties={
                "schemaVersion": {"const": CORE_REPLAY_EVENT_SCHEMA_VERSION},
                "seq": {"type": "integer"},
                "turn": {"type": "integer"},
                "type": {"type": "string"},
                "gameId": {"type": "string"},
                "actorId": {"type": "string"},
                "actionHash": {"type": "string"},
                "previousStateHash": {"type": "string"},
                "nextStateHash": {"type": "string"},
                "timestamp": {"type": "string"},
                "timingsMs": {"type": "object"},
                "payload": {"type": "object"},
            },
        ),
        CORE_RUNNER_SESSION_SCHEMA_VERSION: _object_schema(
            CORE_RUNNER_SESSION_SCHEMA_VERSION,
            required=["schemaVersion", "sessionId", "gameId", "stateHash", "turn", "ok"],
            properties={
                "schemaVersion": {"const": CORE_RUNNER_SESSION_SCHEMA_VERSION},
                "sessionId": {"type": "string"},
                "gameId": {"type": "string"},
                "stateHash": {"type": "string"},
                "turn": {"type": "integer"},
                "ok": {"type": "boolean"},
                "message": {"type": ["string", "null"]},
            },
        ),
        CORE_OBSERVABILITY_SCHEMA_VERSION: _object_schema(
            CORE_OBSERVABILITY_SCHEMA_VERSION,
            required=["event", "requestId", "gameId", "coreVersion", "engineImpl", "timingsMs"],
            properties={
                "event": {"type": "string"},
                "requestId": {"type": ["string", "null"]},
                "gameId": {"type": ["string", "null"]},
                "coreVersion": {"type": "string"},
                "engineImpl": {"type": "string"},
                "stateBytes": {"type": "integer"},
                "observationBytes": {"type": "integer"},
                "legalActionCount": {"type": ["integer", "null"]},
                "timingsMs": {"type": "object"},
            },
        ),
        CATALOGUE_RENDERER_SCHEMA_VERSION: _object_schema(
            CATALOGUE_RENDERER_SCHEMA_VERSION,
            required=[
                "schema_version",
                "game_id",
                "renderer_family",
                "timeline_completeness",
                "public_safe",
            ],
            properties={
                "schema_version": {"const": CATALOGUE_RENDERER_SCHEMA_VERSION},
                "game_id": {"type": "string"},
                "renderer_family": {"type": "string"},
                "renderer_kind": {"type": "string"},
                "timeline_completeness": {"type": "string"},
                "replay_availability": {"type": "string"},
                "visible_frame_count": {"type": "integer"},
                "state_frame_count": {"type": "integer"},
                "move_frame_count": {"type": "integer"},
                "public_safe": {"type": "boolean"},
                "state_hash_valid": {"type": ["boolean", "null"]},
            },
        ),
        CATALOGUE_AVAILABILITY_SCHEMA_VERSION: _object_schema(
            CATALOGUE_AVAILABILITY_SCHEMA_VERSION,
            required=["schema_version", "provider", "model", "game_id", "status", "reason"],
            properties={
                "schema_version": {"const": CATALOGUE_AVAILABILITY_SCHEMA_VERSION},
                "provider": {"type": "string"},
                "model": {"type": "string"},
                "game_id": {"type": "string"},
                "status": {"type": "string"},
                "reason": {"type": ["string", "null"]},
            },
        ),
        SCHEMA_BUNDLE_MANIFEST_SCHEMA_VERSION: _object_schema(
            SCHEMA_BUNDLE_MANIFEST_SCHEMA_VERSION,
            required=[
                "schema_version",
                "core_package_version",
                "schema_bundle_version",
                "schemas",
            ],
            properties={
                "schema_version": {"const": SCHEMA_BUNDLE_MANIFEST_SCHEMA_VERSION},
                "core_package_version": {"type": "string"},
                "core_commit": {"type": ["string", "null"]},
                "schema_bundle_version": {"type": "string"},
                "deterministic_build_id": {"type": "string"},
                "generated_at": {"type": "string"},
                "schemas": {"type": "array"},
            },
        ),
        CATALOGUE_GAME_SCHEMA_VERSION: _object_schema(
            CATALOGUE_GAME_SCHEMA_VERSION,
            required=[
                "schema_version",
                "game_id",
                "display_name",
                "replay_availability",
                "topology",
                "surface",
                "resultContract",
                "help",
                "renderSpec",
                "animationSpec",
            ],
            properties={
                "schema_version": {"const": CATALOGUE_GAME_SCHEMA_VERSION},
                "game_id": {"type": "string"},
                "display_name": {"type": "string"},
                "replay_availability": {"type": "string"},
                "topology": {"type": "object"},
                "surface": {"type": "object"},
                "resultContract": {"type": "object"},
                "help": {"type": "object"},
                "renderSpec": {"type": "object"},
                "animationSpec": {"type": "object"},
            },
        ),
        GAME_TOPOLOGY_SCHEMA_VERSION: _object_schema(
            GAME_TOPOLOGY_SCHEMA_VERSION,
            required=[
                "schemaVersion",
                "mode",
                "controlledPlayers",
                "environmentPlayers",
                "minPlayers",
                "maxPlayers",
                "defaultPlayers",
                "winnerRequired",
                "drawAllowed",
                "placementsAllowed",
                "scoreType",
            ],
            properties={
                "schemaVersion": {"const": GAME_TOPOLOGY_SCHEMA_VERSION},
                "mode": {"enum": ["solo_score", "head_to_head", "multi_seat"]},
                "evaluatedPlayer": {"type": "string"},
                "controlledPlayers": {"type": "array", "items": {"type": "string"}},
                "environmentPlayers": {"type": "array", "items": {"type": "string"}},
                "minPlayers": {"type": "integer", "minimum": 1},
                "maxPlayers": {"type": "integer", "minimum": 1},
                "defaultPlayers": {"type": "integer", "minimum": 1},
                "winnerRequired": {"type": "boolean"},
                "drawAllowed": {"type": "boolean"},
                "placementsAllowed": {"type": "boolean"},
                "scoreType": {"type": "string"},
            },
        ),
        GAME_SURFACE_SCHEMA_VERSION: _object_schema(
            GAME_SURFACE_SCHEMA_VERSION,
            required=["schemaVersion", "arena", "battlefield", "benchmark", "official"],
            properties={
                "schemaVersion": {"const": GAME_SURFACE_SCHEMA_VERSION},
                "arena": {
                    "enum": ["main_arena", "advanced_arena", "table_mode_pending", "disabled"]
                },
                "battlefield": {
                    "enum": ["solo_benchmark", "head_to_head", "multi_seat", "disabled"]
                },
                "benchmark": {"enum": ["enabled", "disabled"]},
                "official": {"enum": ["eligible", "not_eligible", "private_only"]},
                "publicReason": {"type": ["string", "null"]},
            },
        ),
        GAME_RESULT_SCHEMA_VERSION: _object_schema(
            GAME_RESULT_SCHEMA_VERSION,
            required=["schemaVersion", "mode"],
            properties={
                "schemaVersion": {"const": GAME_RESULT_SCHEMA_VERSION},
                "mode": {"enum": ["solo_score", "head_to_head", "multi_seat"]},
                "terminal": {"type": "boolean"},
                "evaluatedPlayer": {"type": "string"},
                "scores": {"type": "object"},
                "primaryScore": {"type": "number"},
                "winner": {"type": ["string", "null"]},
                "draw": {"type": "boolean"},
                "placements": {"type": ["array", "null"], "items": {"type": "string"}},
                "resultType": {"type": "string"},
                "resultTypes": {"type": "array", "items": {"type": "string"}},
                "scoreType": {"type": "string"},
                "winnerRequired": {"type": "boolean"},
                "drawAllowed": {"type": "boolean"},
                "placementsAllowed": {"type": "boolean"},
                "reason": {"type": ["string", "null"]},
            },
        ),
        GAME_HELP_SCHEMA_VERSION: _object_schema(
            GAME_HELP_SCHEMA_VERSION,
            required=[
                "schemaVersion",
                "objective",
                "turnRules",
                "legalActionSummary",
                "scoringSummary",
                "winLossDrawSummary",
                "exampleActions",
            ],
            properties={
                "schemaVersion": {"const": GAME_HELP_SCHEMA_VERSION},
                "objective": {"type": "string"},
                "turnRules": {"type": "array", "items": {"type": "string"}},
                "legalActionSummary": {"type": "string"},
                "scoringSummary": {"type": "string"},
                "winLossDrawSummary": {"type": "string"},
                "hiddenInfoSummary": {"type": ["string", "null"]},
                "firstMoveTip": {"type": ["string", "null"]},
                "exampleActions": {"type": "array"},
                "detailSections": {"type": "array"},
            },
        ),
        GAME_RENDER_SCHEMA_VERSION: _object_schema(
            GAME_RENDER_SCHEMA_VERSION,
            required=[
                "schemaVersion",
                "rendererFamily",
                "seatLayout",
                "hiddenInfo",
                "supportsReplay",
                "supportsLiveFrame",
            ],
            properties={
                "schemaVersion": {"const": GAME_RENDER_SCHEMA_VERSION},
                "rendererFamily": {"type": "string"},
                "boardSize": {"type": ["object", "null"]},
                "seatLayout": {"enum": ["two_sides", "compass", "table_ring", "solo_panel"]},
                "hiddenInfo": {"type": "boolean"},
                "supportsReplay": {"type": "boolean"},
                "supportsLiveFrame": {"type": "boolean"},
            },
        ),
        GAME_ANIMATION_SCHEMA_VERSION: _object_schema(
            GAME_ANIMATION_SCHEMA_VERSION,
            required=[
                "schemaVersion",
                "family",
                "defaultMoveMs",
                "defaultRevealMs",
                "defaultResultMs",
                "reducedMotionBehavior",
                "events",
            ],
            properties={
                "schemaVersion": {"const": GAME_ANIMATION_SCHEMA_VERSION},
                "family": {"type": "string"},
                "defaultMoveMs": {"type": "integer", "minimum": 0},
                "defaultRevealMs": {"type": "integer", "minimum": 0},
                "defaultResultMs": {"type": "integer", "minimum": 0},
                "reducedMotionBehavior": {"enum": ["static_final_state", "fade_only"]},
                "events": {"type": "object"},
            },
        ),
        USAGE_SCHEMA_VERSION: _object_schema(
            USAGE_SCHEMA_VERSION,
            required=["schemaVersion", "usageComplete", "costComplete"],
            properties={
                "schemaVersion": {
                    "enum": [
                        "eslams.usage.model_call.v1",
                        "eslams.usage.summary.v1",
                        USAGE_SUMMARY_SCHEMA_VERSION,
                    ]
                },
                "runId": {"type": "string"},
                "gameId": {"type": "string"},
                "seatId": {"type": "string"},
                "agentId": {"type": "string"},
                "modelId": {"type": "string"},
                "provider": {"type": "string"},
                "turnIndex": {"type": "integer"},
                "inputTokens": {"type": ["integer", "null"]},
                "outputTokens": {"type": ["integer", "null"]},
                "reasoningTokens": {"type": ["integer", "null"]},
                "cachedInputTokens": {"type": ["integer", "null"]},
                "totalTokens": {"type": ["integer", "null"]},
                "latencyMs": {"type": "integer"},
                "costUsd": {"type": ["number", "null"]},
                "usageUnavailableReason": {"type": ["string", "null"]},
                "costUnavailableReason": {"type": ["string", "null"]},
                "timestamp": {"type": "string"},
                "totalInputTokens": {"type": ["integer", "null"]},
                "totalOutputTokens": {"type": ["integer", "null"]},
                "totalCostUsd": {"type": ["number", "null"]},
                "usageComplete": {"type": "boolean"},
                "costComplete": {"type": "boolean"},
                "bySeat": {"type": "object"},
                "byAgent": {"type": "object"},
                "byModel": {"type": "object"},
            },
        ),
        USAGE_SUMMARY_SCHEMA_VERSION: _object_schema(
            USAGE_SUMMARY_SCHEMA_VERSION,
            required=[
                "schemaVersion",
                "usageComplete",
                "costComplete",
                "receiptCount",
                "attemptCount",
                "logicalActionCount",
                "attemptLedgerComplete",
            ],
            properties={
                "schemaVersion": {"const": USAGE_SUMMARY_SCHEMA_VERSION},
                "totalInputTokens": {"type": ["integer", "null"]},
                "totalOutputTokens": {"type": ["integer", "null"]},
                "totalCachedInputTokens": {"type": ["integer", "null"]},
                "totalReasoningTokens": {"type": ["integer", "null"]},
                "totalTokens": {"type": ["integer", "null"]},
                "totalCostUsd": {"type": ["number", "null"]},
                "usageComplete": {"type": "boolean"},
                "costComplete": {"type": "boolean"},
                "receiptCount": {"type": "integer", "minimum": 0},
                "attemptCount": {"type": "integer", "minimum": 0},
                "logicalActionCount": {"type": "integer", "minimum": 0},
                "attemptLedgerComplete": {"type": "boolean"},
                "unavailableReasonCodes": {"type": "array", "items": {"type": "string"}},
                "rateCardReferences": {"type": "array", "items": {"type": "string"}},
                "bySeat": {"type": "object"},
                "byProvider": {"type": "object"},
                "byModel": {"type": "object"},
                "byAttemptKind": {"type": "object"},
                "byStatus": {"type": "object"},
            },
        ),
        CATALOGUE_MODEL_SCHEMA_VERSION: _object_schema(
            CATALOGUE_MODEL_SCHEMA_VERSION,
            required=["schema_version", "provider", "model", "launch_status"],
            properties={
                "schema_version": {"const": CATALOGUE_MODEL_SCHEMA_VERSION},
                "provider": {"type": "string"},
                "model": {"type": "string"},
                "launch_status": {"type": "string"},
                "supported_reasoning_modes": {"type": "array"},
                "accepted_control_fields": {"type": "array"},
                "default_reasoning_track": {"type": ["string", "null"]},
                "reasoning_track_kind": {"type": "string"},
                "unsupported_reasoning_control_reason": {"type": ["string", "null"]},
                "http_agent_payload_guidance": {"type": "object"},
            },
        ),
    }


def _git_commit() -> str | None:
    root = Path(__file__).resolve().parents[3]
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    value = result.stdout.strip()
    return value or None


def _provider_attempt_schema() -> dict[str, Any]:
    nullable_string = {"type": ["string", "null"]}
    nullable_nonnegative_integer = {"type": ["integer", "null"], "minimum": 0}
    fields = [
        "eventId",
        "environment",
        "physicalRunId",
        "officialRunId",
        "modelLaneId",
        "runJobId",
        "shardIndex",
        "caseId",
        "caseAttemptIndex",
        "turnIndex",
        "seatId",
        "logicalActionId",
        "attemptIndex",
        "attemptKind",
        "parentAttemptId",
        "provider",
        "requestedModel",
        "resolvedModel",
        "modelIdentitySource",
        "providerEndpoint",
        "endpointKind",
        "parserVersion",
        "wrapperVersion",
        "status",
        "gatewayRequestId",
        "providerRequestId",
        "httpStatus",
        "errorClass",
        "requestStartedAt",
        "requestCompletedAt",
        "latencyMs",
        "inputTokens",
        "cachedInputTokens",
        "outputTokens",
        "reasoningTokens",
        "totalTokens",
        "reasoningIncludedInOutput",
        "usageSource",
        "usageComplete",
        "estimatedCostUsd",
        "costSource",
        "costComplete",
        "rateCardId",
        "wireParseStatus",
        "actionParseStatus",
        "actionApplied",
        "caseValidForScoring",
    ]
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"https://schemas.eslams.dev/{PROVIDER_ATTEMPT_SCHEMA_VERSION}.json",
        "title": PROVIDER_ATTEMPT_SCHEMA_VERSION,
        "type": "object",
        "additionalProperties": False,
        "required": ["schemaVersion", *fields],
        "properties": {
            "schemaVersion": {"const": PROVIDER_ATTEMPT_SCHEMA_VERSION},
            "eventId": {"type": "string", "minLength": 1},
            "environment": {"type": "string", "minLength": 1},
            "physicalRunId": {"type": "string", "minLength": 1},
            "officialRunId": {"type": "string", "minLength": 1},
            "modelLaneId": {"type": "string", "minLength": 1},
            "runJobId": {"type": "string", "minLength": 1},
            "shardIndex": {"type": "integer", "minimum": 0},
            "caseId": nullable_string,
            "caseAttemptIndex": {"type": "integer", "minimum": 1},
            "turnIndex": {"type": "integer", "minimum": 0},
            "seatId": {"type": "string", "minLength": 1},
            "logicalActionId": {"type": "string", "minLength": 1},
            "attemptIndex": {"type": "integer", "minimum": 1},
            "attemptKind": {"enum": list(ATTEMPT_KINDS)},
            "parentAttemptId": nullable_string,
            "provider": {"type": "string", "minLength": 1},
            "requestedModel": {"type": "string", "minLength": 1},
            "resolvedModel": nullable_string,
            "modelIdentitySource": {
                "enum": [None, "provider_response", "pinned_endpoint"]
            },
            "providerEndpoint": {"type": "string", "format": "uri", "minLength": 1},
            "endpointKind": nullable_string,
            "parserVersion": nullable_string,
            "wrapperVersion": nullable_string,
            "status": {"enum": ["started", "completed", "failed"]},
            "gatewayRequestId": nullable_string,
            "providerRequestId": nullable_string,
            "httpStatus": {
                "type": ["integer", "null"],
                "minimum": 100,
                "maximum": 599,
            },
            "errorClass": {"enum": [None, *FAILURE_CLASSES]},
            "requestStartedAt": {"type": "string", "minLength": 1},
            "requestCompletedAt": nullable_string,
            "latencyMs": nullable_nonnegative_integer,
            "inputTokens": nullable_nonnegative_integer,
            "cachedInputTokens": nullable_nonnegative_integer,
            "outputTokens": nullable_nonnegative_integer,
            "reasoningTokens": nullable_nonnegative_integer,
            "totalTokens": nullable_nonnegative_integer,
            "reasoningIncludedInOutput": {"type": ["boolean", "null"]},
            "usageSource": nullable_string,
            "usageComplete": {"type": "boolean"},
            "estimatedCostUsd": {"type": ["number", "null"], "minimum": 0},
            "costSource": nullable_string,
            "costComplete": {"type": "boolean"},
            "rateCardId": nullable_string,
            "wireParseStatus": nullable_string,
            "actionParseStatus": nullable_string,
            "actionApplied": {"type": "boolean"},
            "caseValidForScoring": {"type": "boolean"},
        },
        "allOf": [
            {
                "if": {"properties": {"status": {"const": "started"}}},
                "then": {
                    "properties": {
                        "requestCompletedAt": {"type": "null"},
                        "latencyMs": {"type": "null"},
                        "httpStatus": {"type": "null"},
                        "errorClass": {"type": "null"},
                        "inputTokens": {"type": "null"},
                        "cachedInputTokens": {"type": "null"},
                        "outputTokens": {"type": "null"},
                        "reasoningTokens": {"type": "null"},
                        "totalTokens": {"type": "null"},
                        "reasoningIncludedInOutput": {"type": "null"},
                        "usageSource": {"type": "null"},
                        "usageComplete": {"const": False},
                        "estimatedCostUsd": {"type": "null"},
                        "costSource": {"type": "null"},
                        "costComplete": {"const": False},
                        "rateCardId": {"type": "null"},
                        "actionApplied": {"const": False},
                        "caseValidForScoring": {"const": False},
                    },
                    "anyOf": [
                        {"properties": {"resolvedModel": {"type": "null"}}},
                        {
                            "properties": {
                                "modelIdentitySource": {"const": "pinned_endpoint"}
                            }
                        },
                    ],
                },
            },
            {
                "if": {
                    "properties": {
                        "caseAttemptIndex": {"minimum": 2},
                        "attemptIndex": {"const": 1},
                    }
                },
                "then": {
                    "properties": {
                        "attemptKind": {"enum": ["case_retry", "action_repair"]}
                    }
                },
            },
            {
                "if": {"properties": {"caseAttemptIndex": {"const": 1}}},
                "then": {"not": {"properties": {"attemptKind": {"const": "case_retry"}}}},
            },
            {
                "if": {"properties": {"status": {"enum": ["completed", "failed"]}}},
                "then": {
                    "properties": {
                        "requestCompletedAt": {"type": "string", "minLength": 1},
                        "latencyMs": {"type": "integer", "minimum": 0},
                    }
                },
            },
            {
                "if": {"properties": {"status": {"const": "failed"}}},
                "then": {"properties": {"errorClass": {"enum": list(FAILURE_CLASSES)}}},
            },
            {
                "if": {"properties": {"status": {"const": "completed"}}},
                "then": {"properties": {"errorClass": {"type": "null"}}},
            },
            {
                "if": {"properties": {"usageComplete": {"const": True}}},
                "then": {
                    "properties": {
                        "inputTokens": {"type": "integer", "minimum": 0},
                        "outputTokens": {"type": "integer", "minimum": 0},
                        "totalTokens": {"type": "integer", "minimum": 0},
                        "reasoningIncludedInOutput": {"type": "boolean"},
                        "usageSource": {"type": "string", "minLength": 1},
                    }
                },
            },
            {
                "if": {"properties": {"costComplete": {"const": True}}},
                "then": {
                    "properties": {
                        "estimatedCostUsd": {"type": "number", "minimum": 0},
                        "costSource": {"type": "string", "minLength": 1},
                        "rateCardId": {"type": "string", "minLength": 1},
                    }
                },
            },
            {
                "if": {"properties": {"actionApplied": {"const": True}}},
                "then": {"properties": {"status": {"const": "completed"}}},
            },
            {
                "if": {"properties": {"caseValidForScoring": {"const": True}}},
                "then": {
                    "properties": {
                        "status": {"const": "completed"},
                        "caseId": {"type": "string", "minLength": 1},
                        "resolvedModel": {"type": "string", "minLength": 1},
                        "modelIdentitySource": {
                            "enum": ["provider_response", "pinned_endpoint"]
                        },
                        "wireParseStatus": {"const": "ok"},
                        "actionParseStatus": {"const": "ok"},
                        "actionApplied": {"const": True},
                    }
                },
            },
        ],
        "x-eslams-invariants": [
            "cachedInputTokens <= inputTokens when both are present",
            (
                "totalTokens = inputTokens + outputTokens + reasoningTokens only when "
                "reasoningIncludedInOutput is false"
            ),
            "pinned_endpoint identity requires resolvedModel = requestedModel",
            (
                "providerEndpoint is an absolute https/mock URI without userinfo, fragments, "
                "or sensitive query parameters"
            ),
        ],
    }


def _object_schema(
    schema_id: str,
    *,
    required: list[str],
    properties: dict[str, Any],
) -> dict[str, Any]:
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"https://schemas.eslams.dev/{schema_id}.json",
        "title": schema_id,
        "type": "object",
        "additionalProperties": True,
        "required": required,
        "properties": properties,
    }
