"""Stable schema version names for eSlams Core contracts."""

from __future__ import annotations

CORE_PACKAGE_VERSION = "0.4.0"
RUNNER_VERSION = f"eslams-runner:{CORE_PACKAGE_VERSION}"
PROTOCOL_VERSION = "eslams-act-v1"
SCHEMA_BUNDLE_VERSION = "eslams-schema-bundle-v2"
CORE_CONTRACT_VERSION = "2.0"
CORE_PROMPT_VERSION = "eslams.core.prompt.v2"
CORE_ACTION_SCHEMA_VERSION = "eslams.core.action_schema.v2"

ARTIFACT_MANIFEST_SCHEMA_VERSION = "eslams.artifact.manifest.v1"
ARTIFACT_VALIDATION_SCHEMA_VERSION = "eslams.artifact.validation.v1"
REPLAY_PUBLIC_SCHEMA_VERSION = "eslams.replay.public.v1"
REPLAY_MANIFEST_SCHEMA_VERSION = "eslams.replay.manifest.v1"
REPLAY_DISPLAY_FRAME_SCHEMA_VERSION = "eslams.replay.display_frame.v1"
PROVIDER_RECEIPT_SCHEMA_VERSION = "eslams.provider.receipt.v1"
EVAL_PLAN_SCHEMA_VERSION = "eslams.eval.plan.v1"
EVAL_PROGRESS_SCHEMA_VERSION = "eslams.eval.progress.v1"
EVAL_RESUME_CHECKPOINT_SCHEMA_VERSION = "eslams.eval.resume_checkpoint.v1"
OFFICIAL_RESULT_SCHEMA_VERSION = "eslams.official.result.v1"
PUBLICATION_BUNDLE_SCHEMA_VERSION = "eslams.publication.bundle.v1"
PUBLICATION_VALIDATION_SCHEMA_VERSION = "eslams.publication.validation.v1"
RUNNER_JOB_SCHEMA_VERSION = "eslams.runner.job.v1"
CATALOGUE_GAME_SCHEMA_VERSION = "eslams.catalogue.game.v1"
CATALOGUE_MODEL_SCHEMA_VERSION = "eslams.catalogue.model.v1"
CATALOGUE_RENDERER_SCHEMA_VERSION = "eslams.catalogue.renderer.v1"
CATALOGUE_AVAILABILITY_SCHEMA_VERSION = "eslams.catalogue.availability.v1"
SCHEMA_BUNDLE_MANIFEST_SCHEMA_VERSION = "eslams.schema.bundle_manifest.v1"
ARENA_ACTION_DESCRIPTOR_SCHEMA_VERSION = "eslams.arena.action_descriptor.v1"
ARENA_EVENT_SCHEMA_VERSION = "eslams.arena.event.v1"
ARENA_LEGAL_ACTIONS_PAGE_SCHEMA_VERSION = "eslams.arena.legal_actions_page.v1"
ARENA_START_RESULT_SCHEMA_VERSION = "eslams.arena.start_result.v1"
ARENA_STEP_RESULT_SCHEMA_VERSION = "eslams.arena.step_result.v1"
CORE_STEP_REQUEST_SCHEMA_VERSION = "eslams.core.step_request.v2"
CORE_STEP_RESPONSE_SCHEMA_VERSION = "eslams.core.step_response.v2"
CORE_PROMPT_PACKAGE_SCHEMA_VERSION = "eslams.core.prompt_package.v2"
CORE_REPLAY_EVENT_SCHEMA_VERSION = "eslams.core.replay_event.v2"
CORE_RUNNER_SESSION_SCHEMA_VERSION = "eslams.core.runner_session.v1"
CORE_OBSERVABILITY_SCHEMA_VERSION = "eslams.core.observability.v1"

SCHEMA_VERSIONS: tuple[str, ...] = (
    ARTIFACT_MANIFEST_SCHEMA_VERSION,
    ARTIFACT_VALIDATION_SCHEMA_VERSION,
    REPLAY_PUBLIC_SCHEMA_VERSION,
    REPLAY_MANIFEST_SCHEMA_VERSION,
    REPLAY_DISPLAY_FRAME_SCHEMA_VERSION,
    PROVIDER_RECEIPT_SCHEMA_VERSION,
    EVAL_PLAN_SCHEMA_VERSION,
    EVAL_PROGRESS_SCHEMA_VERSION,
    EVAL_RESUME_CHECKPOINT_SCHEMA_VERSION,
    OFFICIAL_RESULT_SCHEMA_VERSION,
    PUBLICATION_BUNDLE_SCHEMA_VERSION,
    PUBLICATION_VALIDATION_SCHEMA_VERSION,
    RUNNER_JOB_SCHEMA_VERSION,
    CATALOGUE_GAME_SCHEMA_VERSION,
    CATALOGUE_MODEL_SCHEMA_VERSION,
    CATALOGUE_RENDERER_SCHEMA_VERSION,
    CATALOGUE_AVAILABILITY_SCHEMA_VERSION,
    SCHEMA_BUNDLE_MANIFEST_SCHEMA_VERSION,
    ARENA_ACTION_DESCRIPTOR_SCHEMA_VERSION,
    ARENA_EVENT_SCHEMA_VERSION,
    ARENA_LEGAL_ACTIONS_PAGE_SCHEMA_VERSION,
    ARENA_START_RESULT_SCHEMA_VERSION,
    ARENA_STEP_RESULT_SCHEMA_VERSION,
    CORE_STEP_REQUEST_SCHEMA_VERSION,
    CORE_STEP_RESPONSE_SCHEMA_VERSION,
    CORE_PROMPT_PACKAGE_SCHEMA_VERSION,
    CORE_REPLAY_EVENT_SCHEMA_VERSION,
    CORE_RUNNER_SESSION_SCHEMA_VERSION,
    CORE_OBSERVABILITY_SCHEMA_VERSION,
)


def schema_versions() -> tuple[str, ...]:
    """Return all public contract schema versions in deterministic order."""

    return SCHEMA_VERSIONS
